/**
 * Request validation (EF §3.3 input hygiene). Zod at the edge; handlers below
 * this line only ever see validated data.
 *
 * Note the length caps. They are not cosmetic: an unbounded chat message is a
 * direct token-budget attack, and the budget is a security control (EF §3.4).
 */

import { z } from 'zod';

const uuid = z.string().uuid();
/** Catalog slugs are lowercase kebab, generated by the catalog module. */
const slug = z
  .string()
  .min(1)
  .max(160)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Not a valid slug.');

export const diagnoseBody = z.object({
  brew_session_id: uuid,
  coffee_slug: slug.optional(),
  question: z.string().max(1_000).optional(),
});

export const startingRecipeBody = z.object({
  coffee_slug: slug,
  method: z.enum(['filter', 'immersion', 'espresso']).optional(),
  question: z.string().max(1_000).optional(),
});

export const chatBody = z.object({
  message: z.string().min(1).max(4_000),
  history: z
    .array(
      z.object({
        role: z.enum(['user', 'assistant']),
        text: z.string().max(8_000),
      }),
    )
    .max(20)
    .optional(),
});

export type DiagnoseBody = z.infer<typeof diagnoseBody>;
export type StartingRecipeBody = z.infer<typeof startingRecipeBody>;
export type ChatBody = z.infer<typeof chatBody>;

/** Zod issues -> the shape `badRequest`'s `details` carries elsewhere. */
export const issuesOf = (error: z.ZodError): { path: string; message: string }[] =>
  error.issues.map((issue) => ({ path: issue.path.join('.'), message: issue.message }));
